version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: fasa
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__ENABLE_TLS=false
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

# Define the volume at the bottom
volumes:
  qdrant_data: